### ISSUE TITLE
handle downloadmanager notification click

### ISSUE THREAD

**Issue by zhouzl18** [chiclaim/android-app-update#4]
在onReceive方法中添加：
else if(action.equals(DownloadManager.ACTION_NOTIFICATION_CLICKED)){
            //Toast.makeText(context, "test1111", Toast.LENGTH_SHORT).show();
            Intent dm = new Intent(DownloadManager.ACTION_VIEW_DOWNLOADS);
            dm.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(dm);
        }

清单文件中加入action android:name="android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED"

**Comment by chiclaim** [comment]
恩，有的机型不需要添加（MIUI），有的需要（华为），谢谢提醒。
