### ISSUE TITLE
为什么下载时说明文字显示的是迅雷加速中

### ISSUE THREAD

**Issue by scc897577** [chiclaim/android-app-update#8]
req.setDescription("正在快速下载...");
这里我在怎么设置都是显示的是迅雷正在加速中,找遍这个资源文件,整个项目都没发现有迅雷的字眼儿.请问这个我应该怎么做?

**Comment by chiclaim** [comment]
是的，有的手机系统就内置了迅雷加速功能，所以下载的时候会自动显示。（下载的时候，可以点击进入下载详情页，内置迅雷的），如果国内定制的ROM制定了，就没有办法修改。
